minibangazon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('minisite', include('minisite.urls')),
    path('admin/', admin.site.urls),
]

minisite/urls.py
from django.urls import path
from . import views

app_name = 'minisite'
urlpatterns = [
    # home
    path('', views.index, name='index'),
    path('dogs/new', views.dogNew, name='dog_new'),
]

minisite/models.py
from django.db import models

# Create your models here.
class Dog(models.Model):
  name = models.CharField(max_length=20)
  breed = models.CharField(max_length=20)
  chip_number = models.IntegerField()

  # To add later?
  # owner FK 1:m
  # favorite foods m:m

minisite/forms.py
from django import forms
from django.forms.widgets import SelectDateWidget
from .models import Dog

class DogForm(forms.Form):
  dog_name = forms.CharField(label='Dog name', max_length=20)
  breed = forms.CharField(label='Breed', max_length=20)
  chip_num = forms.IntegerField(label='Chip num')

minisite/views.py
from django.shortcuts import render
from .forms import DogForm
# from .models import *

def index(request):
  return render(request, "minisite/index.html")

def dogNew(request):
  if request.method == "GET":
    print("Fetching the form")
    dog_form = DogForm()
    return render(request, 'minisite/dog_form.html', {"form": dog_form.as_p()})

  if request.method == "POST":
    print("Form stuff!", request.POST)
    # make sure the form inputs are kosher
    form = DogForm(request.POST)
    if form.is_valid():
      cleaned = form.cleaned_data
      cleaned["dog_name"]

minisite/templates/minisite/dog_form.html
{% extends "minisite/index.html" %}

{% block form %}
  <form action="{% url 'minisite:dog_new' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="submit">
  </form>
{% endblock form %}

minisite/templates/minisite/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Form Class Demo</title>
</head>
<body>
  <h1>Some Stuff with Forms and Stuff</h1>

  <form action="{% url 'minisite:dog_new' %}" method="GET">
    <input type="submit" value="register your dog">
  </form>

  {% block form %}{% endblock form %}
</body>
</html>